<div align="center">

  <h2>Laboratório de Matemática Computacional (LaMaC)</h2>

  <h3>Tutorial de Python Científico com Numpy e Pandas</h3>

  Neste tutorial, exploraremos conceitos fundamentais das bibliotecas Numpy e Pandas em Python. Abordaremos as principais estruturas e as funções mais utilizidas de ambas.

</div>

---

### O que é Numpy?

Numpy é uma biblioteca matemática robusta de python, amplamente utilizada nas áreas de análise de dados, ciência de dados, machine learning, entre outras. Com ela é possível realizar operações complexas e manipulações de dados numéricos de maneira mais eficiente do que com os métodos "padrões" da linguagem python.

### Fazendo a importação

Por conveção da comunidade usa-se `as np`.

In [1]:
import numpy as np

### Numpy Array

Uma estrutura de dados da biblioteca numpy, usada para armazenar coleções ordenadas de dados. Os arrays do numpy oferecem um armazenamento mais eficiente e um processamento mais rápido do que o tipo `list`, além de possuirem métodos numéricos, estatísticos e de álgebra linear.

In [3]:
lista = [1, 2, 3, 4, 5]

arr = np.array(lista)

print(type(lista))
print(type(arr))
print("Somatório dos números da lista:", arr.sum())
print("Maior número da lista:", arr.max())
print("Menor número da lista:", arr.min())
print("Média dos números da lista:", arr.mean())

<class 'list'>
<class 'numpy.ndarray'>
Somatório dos números da lista: 15
Maior número da lista: 5
Menor número da lista: 1
Média dos números da lista: 3.0


Os arrays do numpy podem ser tanto unidimensionais como também multidimensionais, com arrays bidimensionais podendo ser interpretados como matrizes. O atributo _shape_ indica o número de dimensões e a magnitude de cada uma (no caso de um array 2d, isso pode ser visto como o número de linhas e o número de colunas).

In [19]:
lista1 = [1, 2, 3]
lista2 = [4, 5, 6]
lista3 = [7, 8, 9]

matrix = np.array([lista1, lista2, lista3])

print(type(matrix))
print("Número de linhas (n) e de colunas (m) da matriz: (n, m) =", matrix.shape)
print("Diagonal principal da matriz:", matrix.diagonal())

<class 'numpy.ndarray'>
Número de linhas (n) e de colunas (m) da matriz: (n, m) = (3, 3)
Diagonal principal da matriz: [1 5 9]


### Salvando e carregando arrays

O numpy tem métodos para salvar arrays como arquivos de extensão `.npy`, bem como carregar esses arquivos em variáveis do tipo array, preservando os dados e a estrutura. Essa funcionalidade é bastante útil para a reutilização e prevenção a perda dos dados.

In [ ]:
# Cria uma matriz de zeros 3x5 
matrix = np.zeros((3, 5))

print(matrix)
print(matrix.shape)

np.save('arquivo.npy', matrix)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
(3, 5)


Carregando o arquivo

In [ ]:
new_matrix = np.load('arquivo.npy')

print(new_matrix)
print(new_matrix.shape)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
(3, 5)


### Numpy random

Um módulo da biblioteca numpy que possui métodos para manipulação de números aleatórios. É particularmente útil para trabalhar com operações probabilísticas.

É possível gerar números aleatórios

In [37]:
random_num = np.random.randint(1, 20)

random_matrix = np.random.rand(3,4)

print('Número inteiro aleatório entre 1 e 20:', random_num)

print('Matriz de números aleatórios entre 0 e 1:\n', random_matrix)

Número inteiro aleatório entre 1 e 20: 8
Matriz de números aleatórios entre 0 e 1:
 [[0.67599151 0.43284283 0.89588985 0.32467139]
 [0.56333186 0.45145263 0.04820304 0.12787257]
 [0.60996918 0.88476018 0.05071654 0.85186441]]


Também é possível selecionar um item aleatoriamente de um conjunto de dados

In [43]:
persons = np.array(['Joaquim', 'Maria', 'Pedro', 'Paulo', 'Antônia', 'Larissa'])

chosen = np.random.choice(persons)

print('A pessoa sorteada foi:', chosen)

A pessoa sorteada foi: Pedro


---